# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "203e48d916d039c8496ab10f7e87c778"
name = "CartPulse"
application_url = "https://cartpulse.kaswebtechsolutions.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update", "checkouts/create" ]
  uri = "/webhooks/cart/abandoned"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,write_products,write_script_tags"

[auth]
redirect_urls = [ "https://cartpulse.kaswebtechsolutions.com/auth/callback" ]
