// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/cart-activity/checkout-sync": {
    params: {};
  };
  "/webhooks/cart-activity/order-sync": {
    params: {};
  };
  "/webhooks/cart-activity/added": {
    params: {};
  };
  "/cart-activity-tracker.js": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/api/cart-activity-capture": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/cart/abandoned": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/unsubscribe": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/cart-activity-script": {
    params: {};
  };
  "/app/register-webhooks": {
    params: {};
  };
  "/app/billing-return": {
    params: {};
  };
  "/app/email-settings": {
    params: {};
  };
  "/app/cart-activity": {
    params: {};
  };
  "/app/inject-script": {
    params: {};
  };
  "/app/outreach": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/reports": {
    params: {};
  };
  "/app/carts": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/cart-activity/checkout-sync" | "/webhooks/cart-activity/order-sync" | "/webhooks/cart-activity/added" | "/cart-activity-tracker.js" | "/webhooks/app/scopes_update" | "/api/cart-activity-capture" | "/webhooks/app/uninstalled" | "/webhooks/cart/abandoned" | "/webhooks/orders/create" | "/unsubscribe" | "/auth/login" | "/auth/*" | "/app" | "/app/cart-activity-script" | "/app/register-webhooks" | "/app/billing-return" | "/app/email-settings" | "/app/cart-activity" | "/app/inject-script" | "/app/outreach" | "/app/billing" | "/app/reports" | "/app/carts";
  };
  "routes/webhooks.cart-activity.checkout-sync.tsx": {
    id: "routes/webhooks.cart-activity.checkout-sync";
    page: "/webhooks/cart-activity/checkout-sync";
  };
  "routes/webhooks.cart-activity.order-sync.tsx": {
    id: "routes/webhooks.cart-activity.order-sync";
    page: "/webhooks/cart-activity/order-sync";
  };
  "routes/webhooks.cart-activity.added.tsx": {
    id: "routes/webhooks.cart-activity.added";
    page: "/webhooks/cart-activity/added";
  };
  "routes/cart-activity-tracker[.]js.tsx": {
    id: "routes/cart-activity-tracker[.]js";
    page: "/cart-activity-tracker.js";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/api.cart-activity-capture.tsx": {
    id: "routes/api.cart-activity-capture";
    page: "/api/cart-activity-capture";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.cart.abandoned.tsx": {
    id: "routes/webhooks.cart.abandoned";
    page: "/webhooks/cart/abandoned";
  };
  "routes/webhooks.orders.create.tsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/unsubscribe.tsx": {
    id: "routes/unsubscribe";
    page: "/unsubscribe";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/cart-activity-script" | "/app/register-webhooks" | "/app/billing-return" | "/app/email-settings" | "/app/cart-activity" | "/app/inject-script" | "/app/outreach" | "/app/billing" | "/app/reports" | "/app/carts";
  };
  "routes/app.cart-activity-script.tsx": {
    id: "routes/app.cart-activity-script";
    page: "/app/cart-activity-script";
  };
  "routes/app.register-webhooks.tsx": {
    id: "routes/app.register-webhooks";
    page: "/app/register-webhooks";
  };
  "routes/app.billing-return.tsx": {
    id: "routes/app.billing-return";
    page: "/app/billing-return";
  };
  "routes/app.email-settings.tsx": {
    id: "routes/app.email-settings";
    page: "/app/email-settings";
  };
  "routes/app.cart-activity.tsx": {
    id: "routes/app.cart-activity";
    page: "/app/cart-activity";
  };
  "routes/app.inject-script.tsx": {
    id: "routes/app.inject-script";
    page: "/app/inject-script";
  };
  "routes/app.outreach.tsx": {
    id: "routes/app.outreach";
    page: "/app/outreach";
  };
  "routes/app.billing.tsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.reports.tsx": {
    id: "routes/app.reports";
    page: "/app/reports";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.carts.tsx": {
    id: "routes/app.carts";
    page: "/app/carts";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.cart-activity.checkout-sync": typeof import("./app/routes/webhooks.cart-activity.checkout-sync.tsx");
  "routes/webhooks.cart-activity.order-sync": typeof import("./app/routes/webhooks.cart-activity.order-sync.tsx");
  "routes/webhooks.cart-activity.added": typeof import("./app/routes/webhooks.cart-activity.added.tsx");
  "routes/cart-activity-tracker[.]js": typeof import("./app/routes/cart-activity-tracker[.]js.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/api.cart-activity-capture": typeof import("./app/routes/api.cart-activity-capture.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.cart.abandoned": typeof import("./app/routes/webhooks.cart.abandoned.tsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.tsx");
  "routes/unsubscribe": typeof import("./app/routes/unsubscribe.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.cart-activity-script": typeof import("./app/routes/app.cart-activity-script.tsx");
  "routes/app.register-webhooks": typeof import("./app/routes/app.register-webhooks.tsx");
  "routes/app.billing-return": typeof import("./app/routes/app.billing-return.tsx");
  "routes/app.email-settings": typeof import("./app/routes/app.email-settings.tsx");
  "routes/app.cart-activity": typeof import("./app/routes/app.cart-activity.tsx");
  "routes/app.inject-script": typeof import("./app/routes/app.inject-script.tsx");
  "routes/app.outreach": typeof import("./app/routes/app.outreach.tsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.tsx");
  "routes/app.reports": typeof import("./app/routes/app.reports.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.carts": typeof import("./app/routes/app.carts.tsx");
};